### ISSUE TITLE
Error when running with pre-trained 90% model 

### ISSUE THREAD

**Issue by Yulong663** [tariks/peakachu#13]
Hi~
When i running with peakachu 90% models with almost 1700 Million intra-chromosomal reads, it didn't work as expected,and all 
error messages are below, hope for your useful reply~

————————————————
HiC version:  8
scoring matrix chr9
num candidates 0
Traceback (most recent call last):
  File "/media/wjn/zzp/peakachu/3dgenome/bin/peakachu", line 4, in <module>
    __import__('pkg_resources').run_script('peakachu==1.1.4', 'peakachu')
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/EGG-INFO/scripts/peakachu", line 80, in <module>
    run()
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/EGG-INFO/scripts/peakachu", line 76, in run
    args.func(args)
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/score_genome.py", line 58, in main
    result, R = X.score(thre=args.minimum_prob)
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py", line 75, in score
    p, clist = self.getwindow(coords)
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py", line 65, in getwindow
    fts = np.vstack((i for i in fts))
  File "<__array_function__ internals>", line 6, in vstack
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.20.3 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.20.3 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/peakachu-1.1.4-py3.7.egg/peakachu/scoreUtils.py:65: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  fts = np.vstack((i for i in fts))
————————————————————

Thanks in advance,
Mike

**Comment by Yulong663** [comment]
Is there anyone could do me a favor :) @tariks @XiaoTaoWang

**Comment by XiaoTaoWang** [comment]
Hi, Mike, one potential reason for this error is that the KR normalization of the chromosome 9 failed during the .hic file generation. My suggestion is converting your .hic into .cool using `hic2cool <https://github.com/4dn-dcic/hic2cool>`_ and balancing the .cool file using ``cooler balance``, then use this .cool file as input and run peakachu again. According to my experience, ``cooler balance`` is more stable than juicer's KR normaization.

Best,

Xiaotao

**Comment by Yulong663** [comment]
Id do helps for the probelm. Thanks a lot ! :+1:

**Comment by Yulong663** [comment]
It do helps for solving the probelm. Thanks a lot ! +1
