### ISSUE TITLE
The predicted location information of the loop file exceeds the size of the chromosomes of the genome

### ISSUE THREAD

**Issue by wbszhu** [tariks/peakachu#15]
Hi,@XiaoTaoWang 
I have some trouble using peakachu: the predicted location information of the loop file exceeds the size of the chromosomes of the genome.
Please check details with this note
https://98c96260.wiz06.com/wapp/pages/view/share/s/2oOm9w0OKN7H2rKMlH1jJYHg2zwMvw3Suk9K28lqIb26pO9q

Thanks for your reply.
LuZhang.

**Comment by XiaoTaoWang** [comment]
Hi, because your Hi-C matrix is at 5kb, you should also set "-r/--resolution" to "5000" when you run "peakachu score_chromosome" and "peakachu pool".

**Comment by wbszhu** [comment]
Thanks a lot.
