### ISSUE TITLE
loops at resolutions other than 10kb

### ISSUE THREAD

**Issue by oriolfornes** [tariks/peakachu#5]
Hi,

If I wish to call loops at, for example, 5kb resolution, do I need to retrain Peakachu or can I still use the models trained on `Rao2014-GM12878-MboI-allreps-filtered.10kb.cool`?

Thank you in advance!

P.S. I love the name of the tool :)

**Comment by tariks** [comment]
Thank you for your question! yes, you should train new models specific for 5kb maps. Other parameters like window size can stay the same for the most part. Good luck!

**Comment by YvesXu** [comment]
Hi, I found that the features in Xtrain and Xfake  do not contain their own features. Is this to prove that the chromosome loop can be predict from other chromosomes? Or something else?

 "train_models.py" line 75  (v for k, v in positive_class.items() **if k != chromname**))

Thank you!
