### ISSUE TITLE
if k != chromname

### ISSUE THREAD

**Issue by YvesXu** [tariks/peakachu#6]
Hi, I found that the features in Xtrain and Xfake do not contain their own features. Is this to prove that the chromosome loop can be predict from other chromosomes? Or something else?

"train_models.py" line 75 (v for k, v in positive_class.items() if k != chromname))

Thank you!

**Comment by tariks** [comment]
This is to prevent overfitting. When training and predicting are happening in the same dataset, a separate model is made for each chromosome, and this model excludes that chromosome during the training phase.
